### ISSUE TITLE
mapping = (iou > 0.5).nonzero(as_tuple=False)

### ISSUE THREAD

**Issue by BIT-MJY** [EdwardLeeLPZ/PowerBEV#2]
Hi @EdwardLeeLPZ ,

I'm sorry to bother you again. Could you please tell me how to choose the proper threshold (0.5) in [mapping = (iou > 0.5).nonzero(as_tuple=False)](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/metrics.py#L191)  of the `metrics.py` since it affects the results seriously? Thanks!

**Comment by EdwardLeeLPZ** [comment]
> Hi @EdwardLeeLPZ ,
> 
> I'm sorry to bother you again. Could you please tell me how to choose the proper threshold (0.5) in [mapping = (iou > 0.5).nonzero(as_tuple=False)](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/metrics.py#L191) of the `metrics.py` since it affects the results seriously? Thanks!

Hello @BIT-MJY ,

I didn't make any change in the `metrics.py` but just follow the existing settings used in [FIERY](https://github.com/wayveai/fiery/blob/master/fiery/metrics.py#182). And I also think this threshold should not be changed for a fair comparison.

**Comment by BIT-MJY** [comment]
Get it. Thanks!
