### ISSUE TITLE
Excuse me, dear author! Why transposes the flow_offset[0] and flow_offset[1]?

### ISSUE THREAD

**Issue by WangzcBruce** [EdwardLeeLPZ/PowerBEV#6]
![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/45158420/7075ed7c-f1a2-422b-ab79-f57a4764c19a)
Excuse me, dear author! Why transposes the flow_offset[0] and flow_offset[1]?
While the related codes in the fiery don't take this action.
![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/45158420/e0bc863b-4a25-4631-9801-c0d857630e2d)

**Comment by EdwardLeeLPZ** [comment]
Hi,

The use of transposes is to match the definition of offset in [GT generation](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/data.py#L388-L389).
![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/49630295/16b9ff2f-244c-4d53-84df-fb1b75663fcb)
The definition here is somewhat trivial, but actually doesn't affect the warped instance segmentation.
