### ISSUE TITLE
RuntimeError: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by pupu-chenyanyan** [EdwardLeeLPZ/PowerBEV#7]
Dear authors:
   Hi ! @EdwardLeeLPZ 
 when i run the train.py with  two gpus, I met the wrong, ie,
File "XXX/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1334, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size, authoritative_rank)
showed  “Tensors must be CUDA and dense".
However,I examine the  parameter of tensors, this is a list where all elements are on cuda: 0.Hence, I do not know what's wrong？Thanks！

**Comment by Viclea** [comment]
![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/110590184/a80694cd-e745-4c7f-9e15-5a52c25ec54b)
You can comment these lines in trainer.py
